name: Build and deploy native image
on:
  push:
    branches:
      - master
      - dev
jobs:
    build-and-deploy:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install GraalVM
              uses: DeLaGuardo/setup-graalvm@3.0
              with:
                graalvm-version: '21.1.0.java11'
            - name: Cache local Maven repository
              uses: actions/cache@v2
              with:
                path: ~/.m2/repository
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                  ${{ runner.os }}-maven-
            - name: Test GraalVM installation
              run: java -version
            - name: Install native-image
              run: |
                echo
                gu install native-image
            - name: Build native image
              run: ./build.sh
            - name: Get Azure credential
              run : echo "::set-output name=login_cred::${{ secrets.DEV_01 }}"
            - name: Login to Azure
              uses: azure/login@v1.1
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}
            - name: 'Deploy to Azure Function'
              uses: Azure/functions-action@v1.4.0
              with:
                app-name: ${{ secrets.AZ_FUNCTION_NAME_APP }}
                package: target/native_spring_function.zip
